# Generated by Django 4.0.4 on 2022-05-28 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_hell', models.IntegerField(verbose_name='Номер зала')),
                ('num_places', models.IntegerField(verbose_name='Количество Мест')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_busy', models.BooleanField(default=False, verbose_name='Занято ли место?')),
                ('num_place', models.IntegerField(verbose_name='Номер Места')),
                ('num_hell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='places.hell')),
            ],
        ),
    ]
