# Generated by Django 4.0.4 on 2022-05-28 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hell',
            name='num_free_places',
        ),
        migrations.RemoveField(
            model_name='hell',
            name='num_occup_places',
        ),
        migrations.AlterField(
            model_name='place',
            name='is_busy',
            field=models.BooleanField(default=False, verbose_name='Занято ли место?'),
        ),
    ]
