# Generated by Django 4.0.4 on 2022-05-28 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cashier', models.CharField(max_length=200, verbose_name='Имя кассира')),
                ('is_regular', models.BooleanField(verbose_name='Постояный ли клиент')),
                ('num_sales', models.IntegerField(default=0, verbose_name='Количество продаж')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10, verbose_name='Номер телефона')),
                ('name_client', models.CharField(max_length=200, verbose_name='Имя клиента')),
                ('is_regular', models.BooleanField(verbose_name='Постояный ли клиент')),
                ('num_buys', models.IntegerField(default=0, verbose_name='Количество покупок')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('num_ticket', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер билета')),
                ('num_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.session')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sells.cashier')),
                ('num_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sells.ticket')),
                ('phone_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sells.client')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place')),
            ],
        ),
    ]
